source 'https://github.com/CocoaPods/Specs.git'

target 'saorsa.PXQSpinner', :exclusive => true do
  pod "saorsa.PXQSpinner", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "saorsa.PXQSpinner", :path => "../"

  
end
